# Generated by Django 4.1.4 on 2022-12-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Bk', 'Black'), ('W', 'White'), ('Y', 'Yellow')], max_length=2)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'color',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/photos/product')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.price')),
            ],
            options={
                'verbose_name': 'productInfo',
                'verbose_name_plural': 'productInfo',
            },
        ),
    ]
