# Generated by Django 4.1.4 on 2022-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
