# Generated by Django 4.1.4 on 2022-12-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_color_remove_productinfo_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='product_name',
            new_name='name',
        ),
    ]
